services:
  db:
    image: postgres:16
    container_name: demano-kofi-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    container_name: demano-kofi-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  minio-init:
    image: quay.io/minio/mc:latest
    container_name: demano-kofi-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do sleep 1; done;
      /usr/bin/mc mb --ignore-existing myminio/${STORAGE_BUCKET};
      /usr/bin/mc anonymous set download myminio/${STORAGE_BUCKET};
      exit 0;
      "
  mailpit:
    image: axllent/mailpit
    container_name: demano-kofi-mailpit
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - '${SMTP_PORT}:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  redis:
    image: redis:8.10.1-trixie
    container_name: demano-kofi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: demano-kofi-worker
    depends_on:
      - redis
      - db
      - minio
    environment:
      NODE_ENV: development
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_REGION: ${STORAGE_REGION}
      STORAGE_BUCKET: ${STORAGE_BUCKET}
      STORAGE_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY_ID}
      STORAGE_SECRET_ACCESS_KEY: ${STORAGE_SECRET_ACCESS_KEY}
      STORAGE_FORCE_PATH_STYLE: ${STORAGE_FORCE_PATH_STYLE}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["bun", "run", "worker"]

volumes:
  pgdata:
  minio-data:
  mailpit-data:
  redis_data: