/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Media {
  createdAt: Generated<Timestamp>;
  fileSize: number;
  height: number | null;
  id: Generated<string>;
  mimeType: string;
  storageKey: string;
  updatedAt: Generated<Timestamp>;
  width: number | null;
}

export interface MediaVariants {
  createdAt: Generated<Timestamp>;
  fileSize: number | null;
  height: number | null;
  id: Generated<string>;
  mediaId: string;
  storageKey: string;
  type: string;
  width: number | null;
}

export interface Member {
  createdAt: Timestamp;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Timestamp;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface ProductCategories {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductCategoryModifierGroups {
  modifierGroupId: string;
  productCategoryId: string;
}

export interface ProductImages {
  isPrimary: Generated<boolean>;
  mediaId: string;
  productId: string;
  sortOrder: Generated<number>;
}

export interface ProductModifierGroups {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isRequired: Generated<boolean>;
  name: string;
  selectionType: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductModifiers {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  modifierGroupId: string;
  name: string;
  priceAdjustment: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface Products {
  categoryId: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  isAvailable: Generated<boolean>;
  isFeatured: Generated<boolean>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductVariants {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  price: number;
  productId: string;
  sku: string;
  updatedAt: Generated<Timestamp>;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  displayUsername: string | null;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface UserProfiles {
  barangay: string | null;
  bio: string | null;
  building: string | null;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp | null;
  firstName: string | null;
  lastName: string | null;
  municipality: string | null;
  phone: string | null;
  province: string | null;
  region: string | null;
  street: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  resendAvailableAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  invitation: Invitation;
  media: Media;
  mediaVariants: MediaVariants;
  member: Member;
  organization: Organization;
  productCategories: ProductCategories;
  productCategoryModifierGroups: ProductCategoryModifierGroups;
  productImages: ProductImages;
  productModifierGroups: ProductModifierGroups;
  productModifiers: ProductModifiers;
  products: Products;
  productVariants: ProductVariants;
  session: Session;
  user: User;
  userProfiles: UserProfiles;
  verification: Verification;
}
